### ISSUE TITLE
All: Review Rebecca's email about ESIP Schema.org Cluster

### ISSUE THREAD

**Issue by rweigel** [hapi-server/tasks#1]
Review Rebecca's email about [ESIP Schema.org Cluster](https://docs.google.com/document/d/1tIlDVnKeocO1E_SSbNaldv0avORfGFdmYDNk_3ub6ik/edit#heading=h.n3stdrckyw1n)

**Comment by jvandegriff** [comment]
we looked at schema.org; if a SPASE record exists for a datasets that is available in SPASE, then SPASE is already creating a landing page for their numeric datasets according to the schema.org JOSN mechanism, and they are findable at Google Dataset Search.

For HAPI datasets that are not in SPASE:  
-we could put them in SPASE, and rely on the above process  
-we could create a whole process to make landing pages for every HAPI dataset that we know about (this would be a large project!)

**Comment by jvandegriff** [comment]
HDRL development is looking to address some of these issues; they are asking for all HAPI metadata, and there may be a centralized push to create some SPASE records out of that (for HAPI data that is not already  in SPASE).

We are closing this since HDRL is taking this up some.
