### ISSUE TITLE
Bob - Follow-up on DAS2

### ISSUE THREAD

**Issue by rweigel** [hapi-server/tasks#2]
Bob reached out to Das2 HAPI Server person Chris P. who will get it up and running again at UIowa

**Comment by rweigel** [comment]
Sent email on 03/28/2024

**Comment by rweigel** [comment]
Chris expect to have complete May 1st.

**Comment by jvandegriff** [comment]
Timestamp issue on one server may have re-emerged (and client fix is now gone)

**Comment by rweigel** [comment]
Having trouble with 

```
curl "https://hapi-server.org/servers-dev/proxy?url=http%3A%2F%2Fplanet.physics.uiowa.edu%2Fdas%2Fdas2Server%2Fhapi%2Fcatalog"
```

Probably proxy issue because the following works

```
curl "https://planet.physics.uiowa.edu/das/das2Server/hapi/catalog"
```

**Comment by jvandegriff** [comment]
This is in the master copy of all.txt
